added recent transactions on HomeScreen
mpawelkiewiczpsk/bank-app-mobile pull request #5
Opened 2024-11-17 18:06 UTC by kurczakooo

![Zrzut ekranu 2024-11-17 190622](https://github.com/user-attachments/assets/3003344c-2cb4-4149-a936-ab587a37ce49)

2024-11-17 20:16 UTC, filip-stepien requested changes
Wygląda elegancko ale wydaje mi się że dobrym pomysłem będzie przekazywanie propsa `amount` jako liczby i formatowanie jej wewnątrz komponentu (dodanie dolarka, przecinków itd.). Podobnie z datą - może bardziej by tu pasował jakiś timestamp?

2024-11-17 20:19 UTC, kamilb13 commented
I dodałbym tablice obiektów z tymi transakcjami i potem już je dynamicznie renderował
coś takiego czy coś:
```
    <ScrollView>
      {transactions.map(transaction => (
        <TransactionsListComponent
          key={transaction.id}
          title={transaction.title}
          date={transaction.date}
          amount={transaction.amount}
          icon={transaction.icon}
        />
      ))}
    </ScrollView>
```

2024-11-18 07:19 UTC, mpawelkiewiczpsk commented
Lista transakcji wygląda bardzo fajnie.
Proponował bym jak wyżej:
- dodać listę z transakcjami i wyświetlać ją za pomocą map()
- dobrze by było dodać skończoną listę ikon i w pojedynczej transakcji trzymać tylko rodzaj transakcji i na podstawie rodzaju transakcji wyświetlać odpowiednią ikonę
- datę powinniśmy trzymać w timestampie żeby na jego podstawie wyświetlać daty (umożliwi nam to również filtrowanie bądź sortowanie po dacie) do obsługi dat polecam bibliotekę day.js

2024-11-25 18:29 UTC, kurczakooo commented
Zrobione, dajcie znać czy jest okej.

2024-11-28 07:06 UTC, merged